resources:
  - name: gitRepo
    type: GitRepo
    configuration:
      path: gitta-jfrog/pipelines-download-files
      gitProvider: github
      branches:
        include: main
    
pipelines:
  - name: download_example
    steps:
      - name: download_files
        type: Bash
        configuration:
          inputResources:
            - name: gitRepo
              trigger: false
          integrations:
            - name: myArtifactory
        execution:
          onStart:
            - sleep 5m
            - ls workspace/
            - ls -la
            - retry_command jfrog rt config --url $int_myArtifactory_url --user $int_myArtifactory_user --apikey $int_myArtifactory_apikey --interactive=false
            - jfrog rt dl --spec specfile.json
            - ls -la
            - cat $HOME/.jfrog/logs/jfrog-cli*
            
